[package]
name = "oracle"
version = "1.0.0"
authors = []

[addresses]
aptos_framework = "0x1"
restaking = "0xb88c2ee5a7d137e135e84c9a4d0e45baadde79aa350bd1639f4f822d0e23e881"
deployer1 = "0xed025f9406fbfa91e133a1765d6fa0a90ed468d2c7ae894835a94a8c279cef9a"
oracle = "0x4cf80d690648534a517991f0266e9522c8c6b6b218ca57703e0db9252217d4e9"

[dev-addresses]
deployer1 = "0x46e6cc3a13792af7f4287c474072d78a84d85fd5597416fc573c81fbcdb216b1"
restaking = "0xc3bb8488ab1a5815a9d543d7e41b0e0df46a7396f89b22821f07a4362f75ddc5"
oracle = "0xab"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.restaking]
git = "https://github.com/A2Dsquad/restaking-contracts"
rev = "eb39c39d09bb8da0add0de074ca22a3d51149e9a"

[dev-dependencies]
